import { createContext, useContext, useId } from "react";
import { cx } from "../../utils/cx";
import "./Field.scss";

const FieldContext = createContext(null);

/**
 * Read the enclosing <Field> wiring (id, aria-describedby, invalid…).
 * Form controls call this to auto-connect to their label/hint/error.
 */
export function useFieldContext() {
  return useContext(FieldContext);
}

/**
 * Form-field wrapper: label + control + hint/error, with all the aria wiring
 * done for you. Any foundation control dropped inside picks it up via context:
 *
 *   <Field label="Correo" hint="Nunca lo compartimos" error={error} required>
 *     <Input type="email" … />
 *   </Field>
 *
 * @param {object} props
 * @param {React.ReactNode} [props.label]
 * @param {React.ReactNode} [props.hint]     help text (hidden while there's an error)
 * @param {React.ReactNode} [props.error]    error message — marks the control invalid
 * @param {boolean} [props.required=false]   asterisk + aria-required on the control
 * @param {boolean} [props.disabled=false]   propagated to the control
 * @param {string}  [props.id]               control id (autogenerated by default)
 */
export default function Field({
  label,
  hint,
  error,
  required = false,
  disabled = false,
  id,
  className = "",
  children,
  ...rest
}) {
  const autoId = useId();
  const controlId = id ?? `ds-field-${autoId}`;
  const hintId = hint ? `${controlId}-hint` : undefined;
  const errorId = error ? `${controlId}-error` : undefined;

  const ctx = {
    id: controlId,
    describedBy: cx(errorId, !error && hintId) || undefined,
    invalid: Boolean(error),
    required,
    disabled,
  };

  return (
    <div
      className={cx(
        "ds-field",
        error && "ds-field--invalid",
        disabled && "ds-field--disabled",
        className,
      )}
      {...rest}
    >
      {label && (
        <label className="ds-field__label" htmlFor={controlId}>
          {label}
          {required && (
            <span className="ds-field__required" aria-hidden="true">
              *
            </span>
          )}
        </label>
      )}

      <FieldContext.Provider value={ctx}>{children}</FieldContext.Provider>

      {error ? (
        <p className="ds-field__error" id={errorId} role="alert">
          {error}
        </p>
      ) : (
        hint && (
          <p className="ds-field__hint" id={hintId}>
            {hint}
          </p>
        )
      )}
    </div>
  );
}

/**
 * Merge Field context into a control's props. Explicit props win.
 * Shared helper for Input/Select/Dropdown/etc.
 */
export function useFieldProps({ id, invalid, disabled, required, describedBy }) {
  const field = useFieldContext();
  return {
    id: id ?? field?.id,
    invalid: invalid ?? field?.invalid ?? false,
    disabled: disabled ?? field?.disabled ?? false,
    required: required ?? field?.required ?? false,
    describedBy: describedBy ?? field?.describedBy,
  };
}
