import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1366, height: 900 }, deviceScaleFactor: 1.25 });
await page.goto("http://localhost:6099/", { waitUntil: "networkidle" });
await page.waitForTimeout(900);
await page.screenshot({ path: "preview/front-hero.png" });
await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
await page.waitForTimeout(700);
await page.screenshot({ path: "preview/front-gallery.png" });
await browser.close();
console.log("ok");
